// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA91S0ePNhXs67rvpIRHnNnsE068da7LKg',
    appId: '1:71765984154:web:03a2444e088a56b8a73023',
    messagingSenderId: '71765984154',
    projectId: 'fireseries-3b992',
    authDomain: 'fireseries-3b992.firebaseapp.com',
    storageBucket: 'fireseries-3b992.appspot.com',
    measurementId: 'G-H4LFT563MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8NE4OzeiMfI0Geq5H7yhAmMrHn2F0IA8',
    appId: '1:71765984154:android:fb45a0feac0bb89da73023',
    messagingSenderId: '71765984154',
    projectId: 'fireseries-3b992',
    storageBucket: 'fireseries-3b992.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw4w2jF7CpbIFZSzqHX1p4FwjMkRBfwc0',
    appId: '1:71765984154:ios:37069233cd8934dca73023',
    messagingSenderId: '71765984154',
    projectId: 'fireseries-3b992',
    storageBucket: 'fireseries-3b992.appspot.com',
    iosBundleId: 'com.example.firebaseSeries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw4w2jF7CpbIFZSzqHX1p4FwjMkRBfwc0',
    appId: '1:71765984154:ios:25db3ada83651e29a73023',
    messagingSenderId: '71765984154',
    projectId: 'fireseries-3b992',
    storageBucket: 'fireseries-3b992.appspot.com',
    iosBundleId: 'com.example.firebaseSeries.RunnerTests',
  );
}
